DELIMITER $$

CREATE PROCEDURE DELETE_BASICINFO(IN p_id varchar(20))
BEGIN
  DELETE FROM BASICINFO WHERE id = p_id;
END;
$$

CREATE PROCEDURE DELETE_MATCHINFO(IN p_id varchar(20))
BEGIN
  DELETE FROM MATCHINFO WHERE id = p_id;
END;
$$

CREATE PROCEDURE DELETE_CHARA_DACK(IN p_id varchar(20))
BEGIN
  DELETE FROM CHARA_DACK WHERE id = p_id;
END;
$$

CREATE PROCEDURE DELETE_ARTIFACT_DACK(IN p_id varchar(20))
BEGIN
  DELETE FROM ARTIFACT_DACK WHERE id = p_id;
END;
$$

CREATE PROCEDURE DELETE_COSTUME_DACK(IN p_id varchar(20))
BEGIN
  DELETE FROM COSTUME_DACK WHERE id = p_id;
END;
$$

CREATE PROCEDURE DELETE_SUBCHARA_INVENTORY(IN p_id varchar(20))
BEGIN
  DELETE FROM SUBCHARA_INVENTORY WHERE id = p_id;
END;
$$

CREATE PROCEDURE DELETE_ARTIFACT_INVENTORY(IN p_id varchar(20))
BEGIN
  DELETE FROM ARTIFACT_INVENTORY WHERE id = p_id;
END;
$$

CREATE PROCEDURE DELETE_COSTUME_INVENTORY(IN p_id varchar(20))
BEGIN
  DELETE FROM COSTUME_INVENTORY WHERE id = p_id;
END;
$$

CREATE PROCEDURE WITHDRAW(IN p_id varchar(20))
BEGIN
  CALL DELETE_BASICINFO(p_id);
  CALL DELETE_MATCHINFO(p_id);
  CALL DELETE_CHARA_DACK(p_id);
  CALL DELETE_ARTIFACT_DACK(p_id);
  CALL DELETE_COSTUME_DACK(p_id);
  CALL DELETE_SUBCHARA_INVENTORY(p_id);
  CALL DELETE_ARTIFACT_INVENTORY(p_id);
  CALL DELETE_COSTUME_INVENTORY(p_id);
END;
$$

DELIMITER ;